
GET http://localhost:3001/users


###
GET http://localhost:3001/users/4
###
POST http://localhost:3001/create;
Content-Type: application/json

{
    "firstName":"Andrey",
    "lastName":"Dolya",
    "age":29,
    "email":"andrey@gmail.com",
    "address":"Tel Aviv"
}


###

PUT http://localhost:3001/users/4
Content-Type: application/json

{
    "type":"lastName",
    "value":"Chanchan"
}